parameters:
    access_key_id: ''
    secret_access_key: ''
    bucket: ''
    region: ''
    filename: ''
    temp_filename: '/data/productsup/tmp.xml'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $accessKeyId: '%access_key_id%'
            $secretAccessKey: '%secret_access_key%'
            $bucket: '%bucket%'
            $region: '%region%'
            $filename: '%filename%'
            $tempFilename: '%temp_filename%'

    Productsup\BinCdeHeinemann\:
        resource: '../src'

    AsyncAws\SimpleS3\SimpleS3Client:
        factory: ['Productsup\BinCdeHeinemann\Export\Infrastructure\Transporter\Factory\S3ClientFactory', 'make']

    League\Flysystem\FilesystemAdapter:
        factory: ['Productsup\BinCdeHeinemann\Export\Infrastructure\Transporter\Factory\S3AdapterFactory', 'make']

    League\Flysystem\Filesystem:
        factory: ['Productsup\BinCdeHeinemann\Export\Infrastructure\Transporter\Factory\FilesystemFactory', 'make']

    Productsup\CDE\Connector\Exception\ExceptionHandlerInterface:
        alias: Productsup\CDE\Connector\Infrastructure\Exception\EventBasedDefaultExceptionHandler

    Productsup\CDE\Connector\Infrastructure\Progress\Countable\EventBasedCountableProgressHandler: ~