parameters:
    'access_key_id': ''
    'secret_access_key': ''
    'bucket': ''
    'region': ''
    'directory_path': ''
#    ftp-remote-file: 'feed.xml'
    xml_receiver_id: 'HEINEMANN-API'
    xml_receiver_email: ''

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $accessKeyId: '%access_key_id%'
            $secretAccessKey: '%secret_access_key%'
            $bucket: '%bucket%'
            $region: '%region%'
            $directoryPath: '%directory_path%'
            #$remoteFile: '%ftp-remote-file%'
            $receiverId: '%xml_receiver_id%'
            $receiverEmail: '%xml_receiver_email%'

    Productsup\BinCdeHeinemann\:
        resource: '../src'

    AsyncAws\S3\SimpleS3Client:
        factory: ['Productsup\BinCdeHeinemann\Export\Infrastructure\Upload\S3ClientFactory', 'make']

    League\Flysystem\AsyncAwsS3\AsyncAwsS3Adapter:
        factory: ['Productsup\BinCdeHeinemann\Export\Infrastructure\Upload\S3AdapterFactory', 'make']

    League\Flysystem\Filesystem:
        factory: ['Productsup\BinCdeHeinemann\Export\Infrastructure\Upload\FilesystemFactory', 'make']

    Productsup\CDE\Connector\Exception\ExceptionHandlerInterface:
        alias: Productsup\CDE\Connector\Infrastructure\Exception\EventBasedDefaultExceptionHandler

    Productsup\CDE\Connector\Infrastructure\Progress\Countable\EventBasedCountableProgressHandler: ~